# Generated by Django 2.2.1 on 2019-06-13 12:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('realname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('orgfile', models.CharField(max_length=120)),
                ('nowfile', models.CharField(max_length=120)),
                ('caption', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=1023)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('filename', models.CharField(max_length=120)),
                ('algorithm', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserService.User')),
            ],
        ),
    ]
