# Generated by Django 2.2.1 on 2019-06-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='language',
            field=models.CharField(default='JAVA', max_length=30),
            preserve_default=False,
        ),
    ]
